apiVersion: v1
kind: Pod
metadata:
  name: serverweb2
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: serverweb3
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
