version: '3'
services:
  web:
    image: httpd
    container_name: server-web
    ports:
      - '8083:80'
    networks:
      - server-net
    depends_on:
      - db
  db:
    image: mysql
    container_name: server-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - server-net

networks:
  server-net:
